CREATE TABLE IF NOT EXISTS offcors_shipments (
  id SERIAL PRIMARY KEY,
  fecha VARCHAR(255),
  no_cierre_despacho INTEGER,
  no_guia_hermeco VARCHAR(255),
  destinatario VARCHAR(255),
  direccion TEXT,
  telefono VARCHAR(255),
  ciudad VARCHAR(255),
  departamento VARCHAR(255),
  nro_entrega VARCHAR(255),
  cedula_cliente VARCHAR(255),
  unidad_embalaje INTEGER,
  canal INTEGER,
  tipo_embalaje VARCHAR(255),
  novedad_despacho TEXT,
  fecha_despacho VARCHAR(255),
  numero_guia_rym VARCHAR(255),
  fecha_entrega VARCHAR(255),
  estado VARCHAR(255),
  guia_subida_rym VARCHAR(50),
  novedad_entrega TEXT,
  novedad_1 TEXT,
  novedad_2 TEXT,
  cliente VARCHAR(100) DEFAULT 'Offcors',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_offcors_guia_rym_entrega UNIQUE (numero_guia_rym, nro_entrega)
);
